[package]
name = "t212-client"
version = "0.1.0"
edition = "2021"
rust-version = "1.83"

# command will be 't212', even though the crate is t212-client
[[bin]]
name = "t212"
path = "src/main.rs"

[dependencies]
base64 = "0.23.1"
clap = { version = "4", features = ["derive"] }
dirs = "6.0.0"
owo-colors = "4.4.0"
rpassword = "7.4.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.0.7"
ureq = { version = "3.2.1", features = ["json"] }
